import { ForgeUpgradeDefinition } from '../types/forge';
import { LIFETIME_EP_STORAGE_KEY } from './explorationConfig';

export const FORGE_UPGRADES_STORAGE_KEY = 'animatrix_forge_upgrades_v3';
export { LIFETIME_EP_STORAGE_KEY };

export const FORGE_UPGRADES_CONFIG: ForgeUpgradeDefinition[] = [
  {
    id: 'alloy_armor',
    name: 'INCREASE HEALTH',
    category: 'HEALTH',
    statLabel: 'HEALTH',
    tagline: 'Make your robot tougher',
    description: 'Increases your robot\'s maximum health in battle.',
    icon: '❤️',
    maxLevel: 10,
    costCurve: [100, 150, 200, 250, 300, 350, 400, 450, 500, 600],
    benefitPerLevelPercent: 5,
    progressionLabels: [
      'Base Health',
      '+5% Health (1 star)',
      '+10% Health (2 stars)',
      '+15% Health (3 stars)',
      '+20% Health (4 stars)',
      '+25% Health (5 stars)',
      '+30% Health (6 stars)',
      '+35% Health (7 stars)',
      '+40% Health (8 stars)',
      '+45% Health (9 stars)',
      '+50% Health (MAX)',
    ],
  },
  {
    id: 'energon_overdrive',
    name: 'FASTER FIRING',
    category: 'FIRE_RATE',
    statLabel: 'FIRE RATE',
    tagline: 'Shoot more shots per second',
    description: 'Decreases reload delay so your robot shoots faster.',
    icon: '🔥',
    maxLevel: 10,
    costCurve: [150, 200, 250, 300, 350, 400, 450, 500, 550, 650],
    benefitPerLevelPercent: 5,
    progressionLabels: [
      'Base Fire Rate',
      '+5% Firing Speed (1 star)',
      '+10% Firing Speed (2 stars)',
      '+15% Firing Speed (3 stars)',
      '+20% Firing Speed (4 stars)',
      '+25% Firing Speed (5 stars)',
      '+30% Firing Speed (6 stars)',
      '+35% Firing Speed (7 stars)',
      '+40% Firing Speed (8 stars)',
      '+45% Firing Speed (9 stars)',
      '+50% Firing Speed (MAX)',
    ],
  },
  {
    id: 'special_core',
    name: 'UPGRADE SPECIAL',
    category: 'SPECIAL',
    statLabel: 'SPECIAL',
    tagline: 'Boost your special power',
    description: 'Powers up your robot\'s special skill and recharges it faster.',
    icon: '✨',
    maxLevel: 10,
    costCurve: [250, 300, 350, 400, 450, 500, 550, 600, 700, 800],
    benefitPerLevelPercent: 5,
    progressionLabels: [
      'Base Special',
      '+5% Special (1 star)',
      '+10% Special (2 stars)',
      '+15% Special (3 stars)',
      '+20% Special (4 stars)',
      '+25% Special (5 stars)',
      '+30% Special (6 stars)',
      '+35% Special (7 stars)',
      '+40% Special (8 stars)',
      '+45% Special (9 stars)',
      '+50% Special (MAX)',
    ],
  },
  {
    id: 'impact_amplifier',
    name: 'INCREASE DAMAGE',
    category: 'DAMAGE',
    statLabel: 'DAMAGE',
    tagline: 'Hit harder with every attack',
    description: 'Increases the damage dealt by your attacks in battle.',
    icon: '⚔️',
    maxLevel: 10,
    costCurve: [200, 250, 300, 350, 400, 450, 500, 550, 600, 700],
    benefitPerLevelPercent: 5,
    progressionLabels: [
      'Base Damage',
      '+5% Damage (1 star)',
      '+10% Damage (2 stars)',
      '+15% Damage (3 stars)',
      '+20% Damage (4 stars)',
      '+25% Damage (5 stars)',
      '+30% Damage (6 stars)',
      '+35% Damage (7 stars)',
      '+40% Damage (8 stars)',
      '+45% Damage (9 stars)',
      '+50% Damage (MAX)',
    ],
  },
];
